export const DELETE_GOAL='DELETE_GOAL';
export const ADD_GOAL='ADD_GOAL';
export const UPDATE_GOAL='UPDATE_GOAL';
export const INIT_GOALS='INIT_GOALS';

export const USER_LOADING='USER_LOADING';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'
export const GET_ERRORS='GET_ERRORS'
export const CLEAR_ERRORS='CLEAR_ERRORS'
